// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbcosjzuzyhezlixujeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiY29zanp1enloZXpsaXh1amV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjUxMzMsImV4cCI6MjA2MjU0MTEzM30.eR5VVA5b22LRAnBHmf7J9LRHvBn_vukeTemnsbkHXM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);